name: Django Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        django-version:
          - "2.1"
          - "2.2"
          - "3.0"
          - "3.1"
          - "3.2"
          - "4.0"
          - "4.1"
          - "4.2"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run tests
      run: tox -e py${{ matrix.python-version }}-django-${{ matrix.django-version }}

    # This step will upload the coverage report to codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # if needed, usually not required for public repos
        fail_ci_if_error: true  # optional: set to true if you want CI to fail when coverage upload fails
